import { QuizQuestion } from "./mockData";

export const generatedQuizQuestions2: QuizQuestion[] = [
  // MODULE 5
  { id: "q-m5-1", quiz_id: "quiz-module-5", question: "What is the cardinal rule of real estate photography?", options: ["Capture the true scale of the space without distorting reality.", "Only take photos at night.", "Always use a DSLR.", "Use ultra-wide lenses to make rooms look huge."], correct_option_index: 0 },
  { id: "q-m5-2", quiz_id: "quiz-module-5", question: "Why should you avoid excessive use of the 'ultra-wide' lens setting?", options: ["It makes the room look too small.", "It causes a fisheye effect that bends straight walls and creates false expectations.", "It costs extra money.", "It is illegal in Nigeria."], correct_option_index: 1 },
  { id: "q-m5-3", quiz_id: "quiz-module-5", question: "What is the most critical element of all property media?", options: ["The watermark.", "The background music.", "The camera brand.", "Lighting."], correct_option_index: 3 },
  { id: "q-m5-4", quiz_id: "quiz-module-5", question: "When taking property photos, what height should the camera ideally be held at?", options: ["Above the head.", "Eye level.", "Floor level.", "Chest height."], correct_option_index: 3 },
  { id: "q-m5-5", quiz_id: "quiz-module-5", question: "Why is chest height preferred for framing a room?", options: ["It hides dirt on the floor.", "It makes the agent look taller.", "It is easier to hold the phone.", "It provides the most natural, balanced perspective, avoiding too much ceiling or floor."], correct_option_index: 3 },
  { id: "q-m5-6", quiz_id: "quiz-module-5", question: "What does 'visual storytelling' mean in real estate media?", options: ["Reading a script during the video.", "Capturing the logical flow of the house so viewers can mentally place their furniture.", "Writing a long caption on Facebook.", "Only taking pictures of the bedrooms."], correct_option_index: 1 },
  { id: "q-m5-7", quiz_id: "quiz-module-5", question: "How does perception dictate pricing?", options: ["Poor media makes clients assume low quality, causing them to negotiate the price downwards.", "Good media allows you to charge triple the market rate.", "The government sets the prices based on pictures.", "Tenants don't care about photos."], correct_option_index: 0 },
  { id: "q-m5-8", quiz_id: "quiz-module-5", question: "What is the enemy of real estate investment?", options: ["Vacancy (lost unrecoverable income).", "Property taxes.", "High definition cameras.", "Tenants with pets."], correct_option_index: 0 },
  { id: "q-m5-9", quiz_id: "quiz-module-5", question: "When recording a video walkthrough, why should you avoid panning too quickly?", options: ["It makes the video file too large.", "It violates Housmata rules.", "It uses too much battery.", "It causes severe motion blur and makes the viewer dizzy."], correct_option_index: 3 },
  { id: "q-m5-10", quiz_id: "quiz-module-5", question: "Should you talk extensively over a video walkthrough?", options: ["Yes, to drown out background noise.", "No, videos must always be completely silent.", "Yes, to entertain the viewer.", "No, let the visual space speak for itself unless providing critical, non-obvious context."], correct_option_index: 3 },

  // MODULE 6
  { id: "q-m6-1", quiz_id: "quiz-module-6", question: "Why should rent collection never be a manual chase?", options: ["It introduces massive inefficiency and emotional friction into the process.", "Landlords prefer to chase it themselves.", "Tenants like to be surprised.", "It takes up phone credit."], correct_option_index: 0 },
  { id: "q-m6-2", quiz_id: "quiz-module-6", question: "How does automation accelerate financial reconciliation?", options: ["By forcing the landlord to calculate it.", "By calling the bank.", "By printing out ledgers automatically.", "By automatically tagging incoming payments to the specific tenant's digital profile instantly."], correct_option_index: 3 },
  { id: "q-m6-3", quiz_id: "quiz-module-6", question: "What is the purpose of a predefined escalation procedure?", options: ["To make the tenant angry.", "To remove emotion from delinquency management and follow the signed agreement.", "To illegally evict the tenant faster.", "To earn more late fees."], correct_option_index: 1 },
  { id: "q-m6-4", quiz_id: "quiz-module-6", question: "What should an iron-clad receipt explicitly contain?", options: ["Just the words 'Rent Paid'.", "Exhaustive details: exact financial period covered, specific property unit, and remaining balance.", "The agent's personal bank details.", "A smiley face."], correct_option_index: 1 },
  { id: "q-m6-5", quiz_id: "quiz-module-6", question: "Why are verbal financial acknowledgments dangerous?", options: ["They damage the phone's microphone.", "They waste time.", "They are legally unenforceable and useless in a dispute.", "They are heavily taxed."], correct_option_index: 2 },
  { id: "q-m6-6", quiz_id: "quiz-module-6", question: "What transforms raw financial data into actionable business intelligence for a landlord?", options: ["A comprehensive quarterly financial statement detailing gross rent, deducted expenses, and net yield.", "A verbal summary over dinner.", "A physical pile of receipts.", "A WhatsApp text saying 'Rent is paid'."], correct_option_index: 0 },
  { id: "q-m6-7", quiz_id: "quiz-module-6", question: "When a landlord receives structured financial reporting, how does their perspective of the manager change?", options: ["They decide to fire the manager.", "They view the manager as an indispensable financial asset rather than just an operational expense.", "They view the manager as a thief.", "They ignore the reports."], correct_option_index: 1 },
  { id: "q-m6-8", quiz_id: "quiz-module-6", question: "If rent is due on the 1st, when should an automated reminder ideally go out?", options: ["Never.", "On the 15th of the preceding month.", "On the 25th of the preceding month.", "On the 2nd."], correct_option_index: 2 },
  { id: "q-m6-9", quiz_id: "quiz-module-6", question: "What happens on Day 14 of an overdue payment in a standard escalation?", options: ["The landlord must apologize to the tenant.", "A formal legal notice of breach of contract is issued.", "The manager ignores it.", "The manager physically removes the tenant."], correct_option_index: 1 },
  { id: "q-m6-10", quiz_id: "quiz-module-6", question: "Precision in receipting prevents:", options: ["The generation of too much paperwork.", "The tenant from renewing the lease.", "The system from crashing.", "Future legal arguments over exactly what a specific payment was intended to cover."], correct_option_index: 3 },

  // MODULE 7
  { id: "q-m7-1", quiz_id: "quiz-module-7", question: "What is an estate manager's primary defensive weapon?", options: ["A large bank account.", "A security guard.", "A loud voice.", "Comprehensive documentation."], correct_option_index: 3 },
  { id: "q-m7-2", quiz_id: "quiz-module-7", question: "Why is complex legal jargon discouraged in Tenancy Agreements?", options: ["It uses too much ink.", "Clarity is vastly more important; an agreement is useless if the tenant cannot understand it.", "Lawyers charge too much for it.", "It makes the document illegal in Nigeria."], correct_option_index: 1 },
  { id: "q-m7-3", quiz_id: "quiz-module-7", question: "Which is NOT one of the five core operational documents?", options: ["Payment Receipts.", "Tenancy Agreement.", "Move-In Inventory Report.", "Agent's Grocery List."], correct_option_index: 3 },
  { id: "q-m7-4", quiz_id: "quiz-module-7", question: "What is the golden rule of inventory management?", options: ["Always estimate the value of the items.", "Don't document cheap items.", "Only document the electronics.", "If an item exists within the property, it must exist on the document."], correct_option_index: 3 },
  { id: "q-m7-5", quiz_id: "quiz-module-7", question: "Why must documents be standardized across a management firm?", options: ["To make them look pretty.", "To ensure consistency, legal compliance, and scalable management.", "To prevent agents from reading them.", "Because the government requires all firms to use the exact same font."], correct_option_index: 1 },
  { id: "q-m7-6", quiz_id: "quiz-module-7", question: "What is the Verification stage of the document lifecycle?", options: ["Uploading the document to social media.", "Both the landlord's rep and the tenant physically inspecting the property and signing the inventory.", "Paying the stamp duty.", "Checking for spelling errors."], correct_option_index: 1 },
  { id: "q-m7-7", quiz_id: "quiz-module-7", question: "How does a platform like Housmata prevent amateur errors?", options: ["By calling tenants directly.", "By centralizing operations and turning documentation into a living, integrated system linked to leases.", "By automatically typing the documents.", "By hiring lawyers automatically."], correct_option_index: 1 },
  { id: "q-m7-8", quiz_id: "quiz-module-7", question: "What happens if a promise is not documented?", options: ["It is still legally binding if there are witnesses.", "Legally, it does not exist and cannot be enforced traceably.", "The tenant gets a free month of rent.", "The landlord must honor it anyway."], correct_option_index: 1 },
  { id: "q-m7-9", quiz_id: "quiz-module-7", question: "Why should documents be stored in the cloud rather than just physical filing cabinets?", options: ["To prevent catastrophic loss by fire, theft, or misplacement.", "It makes it easier to edit signatures.", "Cloud storage is free.", "Because paper is heavy."], correct_option_index: 0 },
  { id: "q-m7-10", quiz_id: "quiz-module-7", question: "How does rigorous documentation increase the valuation of a property management firm?", options: ["It proves they can afford paper.", "It creates a tangible, highly valuable database that doesn't rely on the fleeting memory of individuals.", "It means they have wealthy clients.", "It doesn't increase valuation."], correct_option_index: 1 },

  // MODULE 8
  { id: "q-m8-1", quiz_id: "quiz-module-8", question: "What does it mean to 'be clear, not clever' in communication?", options: ["Use big words to sound smart.", "Always use humor.", "Only communicate via text message.", "Avoid ambiguity and industry jargon that confuses the client."], correct_option_index: 3 },
  { id: "q-m8-2", quiz_id: "quiz-module-8", question: "What is the first step in the structured Communication Flow System?", options: ["The Clarification Phase.", "The Documentation Phase.", "The Alignment Phase.", "The Receipt Phase (acknowledging the inquiry)."], correct_option_index: 3 },
  { id: "q-m8-3", quiz_id: "quiz-module-8", question: "Why must you assume every message will be reviewed by a judge?", options: ["To practice your legal vocabulary.", "To scare the tenant.", "To enforce the principle of traceablity and extreme professionalism.", "Because judges monitor WhatsApp."], correct_option_index: 2 },
  { id: "q-m8-4", quiz_id: "quiz-module-8", question: "How should a professional view a client's strong objection (e.g., 'rent is too high')?", options: ["As a personal insult.", "As a temporary state of incomplete understanding to be clarified.", "As a sign to lower the rent immediately.", "As a final rejection."], correct_option_index: 1 },
  { id: "q-m8-5", quiz_id: "quiz-module-8", question: "Negotiation in professional real estate is about:", options: ["Fighting aggressively to win at the other party's expense.", "Refusing to compromise on anything.", "Tricking the other party.", "Structured alignment of value, expectations, and constraints."], correct_option_index: 3 },
  { id: "q-m8-6", quiz_id: "quiz-module-8", question: "What is a landlord's typical primary motivation during a negotiation?", options: ["Making friends.", "Income stability, long-term asset protection, and tenant reliability.", "Evicting tenants quickly.", "Selling the house."], correct_option_index: 1 },
  { id: "q-m8-7", quiz_id: "quiz-module-8", question: "What is a tenant's typical primary motivation?", options: ["Physical safety, living comfort, and financial predictability.", "Buying the property eventually.", "Damaging the house.", "Paying rent late."], correct_option_index: 0 },
  { id: "q-m8-8", quiz_id: "quiz-module-8", question: "Why is a deal where a desperate tenant agrees to exorbitant rent considered a failed negotiation?", options: ["Because the manager makes too much commission.", "Because it is illegal.", "Because it will inevitably end in default and eviction, causing instability.", "It is actually a successful negotiation."], correct_option_index: 2 },
  { id: "q-m8-9", quiz_id: "quiz-module-8", question: "The Clarification Phase prevents:", options: ["The need for a lease.", "The landlord from spending money.", "Tenants from leaving.", "Misunderstandings from derailing the process by confirming facts."], correct_option_index: 3 },
  { id: "q-m8-10", quiz_id: "quiz-module-8", question: "How does a professional manager handle anxiety from clients?", options: ["By deflecting it using calm, structured, documented communication.", "By ignoring their phone calls.", "By absorbing it and panicking.", "By yelling back."], correct_option_index: 0 },

  // MODULE 9
  { id: "q-m9-1", quiz_id: "quiz-module-9", question: "What are the three primary types of market leads an estate manager deals with?", options: ["Buyers, Sellers, Renters.", "Local, National, International.", "Landlord leads, Tenant leads, Investor leads.", "Government, Corporate, Individual."], correct_option_index: 2 },
  { id: "q-m9-2", quiz_id: "quiz-module-9", question: "What must you emphasize when marketing to a Landlord lead?", options: ["The color of the property.", "Cheap agency fees.", "The safety of the neighborhood.", "Strict financial reporting, tenant screening, and maintenance protocols."], correct_option_index: 3 },
  { id: "q-m9-3", quiz_id: "quiz-module-9", question: "What is the absolute primary marketing tool for generating inquiries?", options: ["The structured Property Listing.", "A billboard.", "A radio ad.", "A business card."], correct_option_index: 0 },
  { id: "q-m9-4", quiz_id: "quiz-module-9", question: "In the digital age, what happens if your property listing is blurry and uninformative?", options: ["The platform deletes it automatically.", "Clients assume your management skills are equally sloppy and ignore you.", "It goes viral.", "Clients will call to ask for better pictures."], correct_option_index: 1 },
  { id: "q-m9-5", quiz_id: "quiz-module-9", question: "What is the first stage of the Lead Funnel?", options: ["Decision.", "Awareness.", "Interest.", "Evaluation."], correct_option_index: 1 },
  { id: "q-m9-6", quiz_id: "quiz-module-9", question: "What is the core philosophy behind a comprehensive content strategy?", options: ["Content goes viral easily.", "It is free to produce.", "People do not trust properties first; they trust the professionals who manage them.", "People trust properties first."], correct_option_index: 2 },
  { id: "q-m9-7", quiz_id: "quiz-module-9", question: "Even with the best personal brand, why do amateur agents often lose lucrative leads?", options: ["They rely on their memory or a chaotic WhatsApp inbox instead of a CRM.", "They charge too much.", "They don't have enough followers.", "They only speak English."], correct_option_index: 0 },
  { id: "q-m9-8", quiz_id: "quiz-module-9", question: "How does the Housmata ecosystem transform property marketing?", options: ["By forcing organization, turning it into a highly predictable, mathematically driven system function.", "By restricting who can view listings.", "By making it a stressful guessing game.", "By doing all the marketing for the agent automatically."], correct_option_index: 0 },
  { id: "q-m9-9", quiz_id: "quiz-module-9", question: "What is 'Direct Acquisition' as a marketing channel?", options: ["Posting on social media.", "Waiting for referrals.", "Paying for Google Ads.", "Proactive field sourcing, attending industry networking events, and directly pitching."], correct_option_index: 3 },
  { id: "q-m9-10", quiz_id: "quiz-module-9", question: "Marketing to a tenant requires emphasizing:", options: ["Financial reporting.", "High investment yields.", "Asset protection.", "Comfort, security, safety, and utility reliability."], correct_option_index: 3 },
];
